name: to test workflow
on: push
jobs:
  hello-world:
    runs-on: self-hosted
    steps:
      - name: hello
        run: echo "hello world"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: print greetings
        run: echo "hello"
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
