name: to test workflow
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello world"
      - name: Check out repository code
        uses: actions/checkout@v3
