name: to test workflow
on: push
jobs:
  hello-world:
    runs-on: self-hosted
    steps:
      - name: hello
        run: echo "hello world"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: print greetings
        run: echo "hello"
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
