name: to test workflow
on: push
jobs:
  hello-world:
    runs-on: self-hosted
    steps:
      - name: hello
        run: echo "hello world"
      - name: check LS before checkout
        run: ls
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: check LS after checkout
        run: sudo apt install tree -y
